export * from './Cat/Cat';
export * from './Cats/Cats';
export * from './ClassComponent/ClassComponent';
export * from './Comments/Comments';
export * from './Dog/Dog';
export * from './Dogs/Dogs';
export * from './Form/Form';
export * from './Header/Header';
export * from './Posts/Posts';
